#!/usr/bin/env python3
"""Build a WordPress import file from the page drafts in content/sv/.

The drafts are kept as HTML so they can be read and reviewed in a diff. This
turns them into a single WXR file that imports through Tools > Import >
WordPress, which gets the titles, slugs, excerpts and ordering right without
anyone pasting four pages by hand.

Pages are imported as DRAFTS. Nothing goes live until someone publishes it.

Usage:
    ./scripts/build-content-wxr.py [--status draft|publish] [--out FILE]

Each source file starts with an HTML comment holding its metadata:

    <!--
    title:    Symboler och förkortningar
    slug:     symboler-och-forkortningar
    excerpt:  One-line summary.
    order:    10
    -->
"""

import argparse
import glob
import os
import re
import sys
from datetime import datetime, timezone

SOURCE_DIR = 'content/sv'
DEFAULT_OUT = 'content/cc-sverige-sidor.wxr'

HEADER_RE = re.compile(r'\A<!--(?P<header>.*?)-->', re.S)
FIELD_RE = re.compile(r'^\s*(?P<key>[a-z_]+):\s*(?P<value>.*?)\s*$', re.M)


def cdata(text):
    """Wrap text in CDATA, splitting any literal ]]> so it stays well formed."""
    return '<![CDATA[' + text.replace(']]>', ']]]]><![CDATA[>') + ']]>'


def parse(path):
    raw = open(path, encoding='utf-8').read()
    match = HEADER_RE.match(raw)

    if not match:
        sys.exit('%s: missing the leading <!-- ... --> metadata comment' % path)

    meta = {m.group('key'): m.group('value')
            for m in FIELD_RE.finditer(match.group('header'))}

    for required in ('title', 'slug'):
        if not meta.get(required):
            sys.exit('%s: metadata is missing "%s"' % (path, required))

    body = raw[match.end():].strip()

    if not body:
        sys.exit('%s: no content after the metadata comment' % path)

    return {
        'title': meta['title'],
        'slug': meta['slug'],
        'excerpt': meta.get('excerpt', ''),
        'order': int(meta.get('order', 0)),
        'content': body,
        'source': path,
    }


def build(pages, status, site_url):
    now = datetime.now(timezone.utc)
    stamp = now.strftime('%Y-%m-%d %H:%M:%S')
    rfc = now.strftime('%a, %d %b %Y %H:%M:%S +0000')

    out = [
        '<?xml version="1.0" encoding="UTF-8" ?>',
        '<!-- Generated by scripts/build-content-wxr.py from %s -->' % SOURCE_DIR,
        '<rss version="2.0"',
        '\txmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"',
        '\txmlns:content="http://purl.org/rss/1.0/modules/content/"',
        '\txmlns:wfw="http://wellformedweb.org/CommentAPI/"',
        '\txmlns:dc="http://purl.org/dc/elements/1.1/"',
        '\txmlns:wp="http://wordpress.org/export/1.2/"',
        '>',
        '<channel>',
        '\t<title>Creative Commons Sverige</title>',
        '\t<link>%s</link>' % site_url,
        '\t<description>Sidutkast for Creative Commons Sverige</description>',
        '\t<pubDate>%s</pubDate>' % rfc,
        '\t<language>sv-SE</language>',
        '\t<wp:wxr_version>1.2</wp:wxr_version>',
        '\t<wp:base_site_url>%s</wp:base_site_url>' % site_url,
        '\t<wp:base_blog_url>%s</wp:base_blog_url>' % site_url,
    ]

    for i, page in enumerate(pages, start=1):
        post_id = 9000 + i
        out += [
            '\t<item>',
            '\t\t<title>%s</title>' % cdata(page['title']),
            '\t\t<link>%s/%s/</link>' % (site_url, page['slug']),
            '\t\t<pubDate>%s</pubDate>' % rfc,
            '\t\t<dc:creator>%s</dc:creator>' % cdata('admin'),
            '\t\t<guid isPermaLink="false">%s?page_id=%d</guid>' % (site_url, post_id),
            '\t\t<description></description>',
            '\t\t<content:encoded>%s</content:encoded>' % cdata(page['content']),
            '\t\t<excerpt:encoded>%s</excerpt:encoded>' % cdata(page['excerpt']),
            '\t\t<wp:post_id>%d</wp:post_id>' % post_id,
            '\t\t<wp:post_date>%s</wp:post_date>' % cdata(stamp),
            '\t\t<wp:post_date_gmt>%s</wp:post_date_gmt>' % cdata(stamp),
            '\t\t<wp:comment_status>%s</wp:comment_status>' % cdata('closed'),
            '\t\t<wp:ping_status>%s</wp:ping_status>' % cdata('closed'),
            '\t\t<wp:post_name>%s</wp:post_name>' % cdata(page['slug']),
            '\t\t<wp:status>%s</wp:status>' % cdata(status),
            '\t\t<wp:post_parent>0</wp:post_parent>',
            '\t\t<wp:menu_order>%d</wp:menu_order>' % page['order'],
            '\t\t<wp:post_type>%s</wp:post_type>' % cdata('page'),
            '\t\t<wp:post_password>%s</wp:post_password>' % cdata(''),
            '\t\t<wp:is_sticky>0</wp:is_sticky>',
            '\t</item>',
        ]

    out += ['</channel>', '</rss>', '']

    return '\n'.join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--status', default='draft', choices=('draft', 'publish'),
                        help='post status for the imported pages (default: draft)')
    parser.add_argument('--out', default=DEFAULT_OUT, help='output file')
    parser.add_argument('--site-url', default='https://creativecommons.se',
                        help='base URL recorded in the export (informational)')
    args = parser.parse_args()

    # Run from the repository root regardless of where this is invoked.
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

    sources = sorted(glob.glob(os.path.join(SOURCE_DIR, '*.html')))

    if not sources:
        sys.exit('no drafts found in %s' % SOURCE_DIR)

    pages = sorted((parse(p) for p in sources), key=lambda p: (p['order'], p['slug']))

    slugs = [p['slug'] for p in pages]
    duplicates = {s for s in slugs if slugs.count(s) > 1}

    if duplicates:
        sys.exit('duplicate slugs: %s' % ', '.join(sorted(duplicates)))

    open(args.out, 'w', encoding='utf-8').write(build(pages, args.status, args.site_url.rstrip('/')))

    print('wrote %s (%d pages, status: %s)' % (args.out, len(pages), args.status))
    for page in pages:
        print('  %3d  %-34s %s' % (page['order'], page['slug'], page['title']))


if __name__ == '__main__':
    main()
